### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by ILOVETOMAKESTUFF** [ILOVETOMAKESTUFF/SaveAspectOS#1]
So the image for the background is blocked for me, so if anyone reads this, tell me how it looks. Thanks!

**Comment by webdev03** [comment]
![image](https://user-images.githubusercontent.com/75148774/155460933-9fb7fcbe-c0c4-4fa9-a84e-1caeecbd514d.png)

**Comment by ILOVETOMAKESTUFF** [comment]
> ![image](https://user-images.githubusercontent.com/75148774/155460933-9fb7fcbe-c0c4-4fa9-a84e-1caeecbd514d.png)

Yikes, I might have to resize it a bit and set `no-repeat` in the CSS. Thanks though!

**Comment by ILOVETOMAKESTUFF** [comment]
What about now?

**Comment by webdev03** [comment]
You can't even read the text (just use a plain/gradient/dark background!!!)
![image](https://user-images.githubusercontent.com/75148774/155869105-8bf63e69-55df-43b4-88d2-5817f9eb9a50.png)

**Comment by ILOVETOMAKESTUFF** [comment]
Yikes, that's even worse! I'll just make it like the first version...

**Comment by webdev03** [comment]
You don't need to make that the background (very bad readability)! Just make it a dark background or something!
